#!/bin/sh
#Alias
#Auto open files
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='feh'
alias -s {mpg,mpeg,avi,ogm,ogv,wmv,m4v,mp4,mov,f4v,mkv}='mplayer'
alias -s {mp3,ogg,wav,flac}='ncmpcpp'
alias -s {html,php,com,net,org,gov}='chrome'
alias -s pdf='zathura'
alias -s chm='xchm'
alias -s {rar,zip,7z,tar}='extract'
alias -s {txt}='v'

# The 'cd' family ------------
alias h='cd ~'
alias home='cd ~' 
alias dotfiles='cd /ntfs-data/.dotFiles/'

#Sett File Edit
alias update='yaourt -Syu'
alias clean='pacman -Rsn $(pacman -Qdtq)'
alias ls='ls --color=auto -h'
alias bashrc='vim ~/.bashrc && source ~/.bashrc'
alias zshrc='vim ~/.zshrc && source ~/.zshrc'
alias rm='rm -r'
alias cp='cp -i -r'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias grep='grep --color=auto'
alias y='yaourt'

#Quickly navigate fav folder
alias inbox='cd /ntfs-data/inbox'
alias book='cd /ntfs-data/docs/'
alias work='cd /ntfs-data/work/'
alias vid='cd /ntfs-data/vids'
alias lang='cd /ntfs-data/docs/lang'
alias build='~/.build/'
alias webcode='cd /opt/lampp/htdocs'
alias dev='cd /ntfs-data/Dropbox/dev/'

#Application
alias urxvt='urxvtc&'
alias gimp='gimp&exit'
alias pidg='pidgin&'
alias achrome='chromium-dev&exit'
alias airc='irssi -n nXqd -w qungdung -c irc.freenode.net'
alias mpd='mpd ~/.mpdconf'
alias amusic='mpd;mpdscribble;ncmpcpp'
alias amplayer='mplayer -utf8'
alias aam90='amixer set Master 70%'
alias aam70='amixer set Master 50%'
alias aam100='amixer set Master 100%'
alias adef="sdcv -u Oxford\ Advanced\ Learner\'s\ Dictionary"
alias asynonym="sdcv -u Moby\ Thesaurus\ II"
alias apc="python2 ~/.scripts/ideone.py"
alias awpa='wpa_supplicant -B -Dwext -i wlan0 -c /etc/wpa_supplicant.conf;ifconfig wlan0 192.168.1.7;route add default gw 192.168.1.1;'
alias make_dwm='makepkg -g --asroot >> PKGBUILD;makepkg -efi --asroot'
#Editor
alias vi='vim'
alias v='vim'
#Navigation
alias ..='cd ..'
alias ~='cd ~'
#Misc
alias go='startx'
alias shutdown='shutdown -h now'
