#!/bin/zsh

#Extract Files
 extract () {
   if [ -f $1 ] ; then
       case $1 in
           *.tar.bz2)   tar xvjf $1    ;;
           *.tar.gz)    tar xvzf $1    ;;
           *.tar.xz)    tar xvJf $1    ;;
           *.bz2)       bunzip2 $1     ;;
           *.rar)       unrar x $1     ;;
           *.gz)        gunzip $1      ;;
           *.tar)       tar xvf $1     ;;
           *.tbz2)      tar xvjf $1    ;;
           *.tgz)       tar xvzf $1    ;;
           *.zip)       unzip $1       ;;
           *.Z)         uncompress $1  ;;
           *.7z)        7z x $1        ;;
           *.xz)        unxz $1        ;;
           *.exe)       cabextract $1  ;;
           *)           echo "\`$1': unrecognized file compression" ;;
       esac
   else
       echo "\`$1' is not a valid file"
   fi
 }
# Twitter
 twit () {
    curl -u Nxqd3051990:reachyourgoal\&7\& -d status="$*" http://twitter.com/statuses/update.xml > /dev/null &2>1 ;
 }
# Flash player - due to flash 64bit can't play in full screen
 mplayer-web () { 
    mplayer /tmp/Flash*;
 }
